[package]
name = "multi_keychain_wallet"
version = "0.0.1"
edition = "2021"
rust-version = "1.63.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bdk_wallet = { version = "2.0.0", default-features = false }
bitcoin = { version = "0.32.6", features = ["serde", "base64"], default-features = false }
miniscript = { version = "12.3.4", features = ["serde"], default-features = false }
serde = { version = "1", features = ["derive"] }

[features]
default = ["std"]
std = ["bitcoin/std", "bitcoin/rand-std", "miniscript/std", "bdk_wallet/std"]
rusqlite = ["bdk_wallet/rusqlite"]

[dev-dependencies.multi_keychain_wallet]
path = "."

[dev-dependencies]
anyhow = "1"
tempfile = "3.21.0"
bdk_electrum = {version = "0.23.1"}
bdk_bitcoind_rpc = {version = "0.22.0"}

[[example]]
name = "keyring"
required-features = ["rusqlite"]

[[example]]
name = "custom_keychain_identifier"
required-features = ["rusqlite"]

[[example]]
name = "default_keychain"
required-features = ["rusqlite"]

[[example]]
name = "electrum_example"

[[example]]
name = "rpc_example"
